### ISSUE TITLE
Active area height failed to pass matching threshold 0.0%

### ISSUE THREAD

**Issue by rocketeer55** [Zggis/dobby#9]
I am trying out this program but I'm running into an issue during step 6, getting the error message: `Active area height failed to pass matching threshold 0.0%, aborting merge.`. This error is then followed by a NullPointerException.

Both sets of input files are WEB-DLs from ATVP, from the same release group. Their resolutions are identical, aspect ratio the same, framerate the same, and their bitrates are very similar. Only difference I can see is dolby vision (profile 5) vs HDR10.

I can share my log file if needed. Looking through the logs, I only see that the HDR version had its 'Active Area' analyzed. I didn't see any steps indicating the 'Active Area' was analyzed on the DV files.

Thanks in advance

**Comment by Zggis** [comment]
Hi rocketeer,
Log file would be helpful, I would like to cleanup the NullPointerException. I am building a new release right now that will support a new environment variable to disable the active area validation, If you are confident the files are identical you can use that to skip the validation.
The active area validation scans the files to check the borders match in a few sample locations. Even if two files are the same resolution and aspect ratio the black borders on the top and bottom could be different. For example, many of the marvel movies are available in standard and IMAX versions of the same resolution. If you scan these files with a tool like MediaInfo they would look almost identical, but the IMAX version would have some scenes where the black borders on the top and bottom shrink to give a larger viewing window.
Once I have the release published I will reply with the info you need to disable the validation.

**Comment by Zggis** [comment]
Alright you can force update your container, v1.0.6 is available on the latest branch.

To skip the active area validation you can add an environment variable AAVALIDATE and set it to false

I also added LOGLEVEL, if you could run it once with that set to TRACE (and AAVALIDATE set to true) and upload your logs here that will help me figure out if there is a bug in the active area validation algorithm.

**Comment by rocketeer55** [comment]
Thanks Zggis! Appreciate the fast response. As far as I can tell, neither the HDR or DV video files have black bars at all - when playing directly in VLC, the video content fills the entire 3840x1606 viewing area (2.35 aspect ratio). Maybe the bug is related to no black bars being present?

I will try first with LOGLEVEL TRACE and provide those here later today, then I will try with AAVALIDATE to see if I can successfully get these videos merged.

Thanks so much!

**Comment by rocketeer55** [comment]
Dobby completed without errors with AAVALIDATE set to false, and I verified the output files and both the HDR and DV profiles look like they turned out correctly. Thank you for this!

Attached is the log file from the failed run with AAVALIDATE true and LOGLEVEL TRACE. Would love if you can take a look, as I think active area validation seems like a feature I'd ideally like to keep enabled if possible.
[dobby copy.log](https://github.com/Zggis/dobby/files/10026586/dobby.copy.log)

Thanks again

**Comment by Zggis** [comment]
Thank you for the logs rocket! The NullPointers are easy enough to clean up. I am going to take a closer look at the active area algorithm. The logs confirm what you said about these files not having black borders so they should pass validation.

DV files are not scanned for active area since their border info can be extracted from the RPU with far less processing, so the algorithm compares against that which in your case caused a discrepancy, probably because some scenes are dark enough to trick it into thinking a border is present when its not. I am going to reconsider that decision, it might be more reliable to do the active area scan on both DV and HDR files at the same timestamps and compare those.

I will post updates here, going to take a few days for me to resolve.

**Comment by rocketeer55** [comment]
Yeah I think something funky is going on with the active height values being used in `src/main/java/com/zggis/dobby/batch/processors/MergeValidationProcessor.java`. I tore open the code and added in some log messages to print the value of `rpuActiveHeight` and each value of `conversion.getStandardFile().getActiveArea().getActiveAreaHeights()` as it loops through.
`rpuActiveHeight` had a value of -2, and `conversion.getStandardFile().getActiveArea().getActiveAreaHeights()` was just a list full of 0's.
Let me know if there's anything you want me to test against my files in particular!

**Comment by Zggis** [comment]
Yea, the issue is actually with the RPUBorderInfoProcessor which extracts the active area information from the DV RPU file. With the file you were using, the RPU files extracted from the DV files did not contain any X/Y offsets for the border, so they stayed at the default -1 and when added together became -2 as you saw above.

I changed the default values so if it does not find any X/Y offsets in the RPU it will assume there are no borders and set the values to 0 which should allow it to pass validation assuming there are no borders detected in the matching HDR file.

I tested it with DV files that have offsets and some without, seems to be working now.

These changes are reflected in v1.0.7 which I have just released.
